version: 2.1

orbs:
heroku: circleci/heroku@1.2.6

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main-test.py
  deploy: # this can be any name you choose
  executor: heroku/default # use the default executor defined within the orb
  steps:
    - attach_workspace:
        at: ~/circleci-python
    - heroku/deploy-via-git:
        force: true

workflows:
build_test_deploy:
jobs:
  - build_and_test
  - deploy:
      requires:
        - build_and_test # only deploy if the build_and_test job has completed
      filters:
        branches:
          only: master