version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python3 -m pip install --upgrade --user pip
            pip install --user -r requirements.txt
      - run: python3 main.py

  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python3 -m pip install --upgrade --user pip
            pip install --user -r requirements.txt
      - run: python3 main-test.py

  deploy:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python3 -m pip install --upgrade --user pip
            pip install --user -r requirements.txt
      - run: echo "Deploying to production"

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
